#!/bin/env bash
echo "OK"
mysql -u $MYSQL_USER -p$MYSQL_PASSWORD -e "
CREATE DATABASE $MYSQL_DATABASE;
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO
    $MYSQL_USER@localhost IDENTIFIED BY '$MYSQL_PASSWORD'
";
